### ISSUE TITLE
Known Issues?

### ISSUE THREAD

**Issue by anseltaft** [secretstache/genesis-foundation#2]
Rich,

Matt Mizwicki pointed me to this repo today and I wondered if there were any known issues with the child theme? I'm a front end guy and wouldn't mind giving it a roll on an upcoming site. I just need to vet how production-ready it is.

Cheers

**Comment by secretstache** [comment]
It's ok to throw on a test site to play around with it, but it does require quite a bit of tweaking to get working. I haven't had a ton of time to update, but I hope to have it production ready by March

**Comment by anseltaft** [comment]
Cool - thank you for the heads up.
